version: '3'

volumes:
  pg_volume:

services:
  web:
    build: .
    container_name: Django
    command: python src/manage.py runserver 0.0.0.0:20000
    volumes:
      - ./src:/code/src
      - ./logs:/code/logs
    ports:
      - 20000:20000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    container_name: Postgres
    image: postgres:12-alpine
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main

  pgadmin:
    container_name: Pg_admin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - ./sql/dumps:/var/lib/pgadmin/storage/
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: koro6@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5444:80

  redis :
    container_name: Redis
    image: redis:4.0.14-alpine

  celery:
    build: .
    container_name: Celery
    command: bash -c "cd src && celery -A project worker -l INFO -n celery@%h"
    volumes:
      - ./src:/code/src
      - ./logs:/code/logs
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    container_name: Celery-beat
    command: bash -c "cd src && celery -A project beat"
    volumes:
      - ./src:/code/src
      - ./logs:/code/logs
    depends_on:
      - web
      - redis

  flower:
    build: .
    container_name: Celery-flower
    command: bash -c "cd src && celery -A project --broker=redis://redis:6379/0 flower --port=5555"
    ports:
      - 20001:5555
    volumes:
      - ./src:/code/src
      - ./logs:/code/logs
    depends_on:
      - web
      - redis
