version: '3'

volumes:
  pg_volume:

services:
  web:
    build: .
    container_name: Django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/code/project
      - ./logs:/code/logs
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    container_name: Postgres
    image: postgres
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - 5432:5432

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - ./sql/dumps:/var/lib/pgadmin/storage/
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: koro6@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

  redis :
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  celery:
    build: .
    container_name: celery
    command: celery -A project worker -l INFO
    volumes:
      - ./project:/code/project
      - ./logs:/code/logs
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A project beat
    volumes:
      - ./project:/code/project
      - ./logs:/code/logs
    depends_on:
      - web
      - redis

  flower:
    build: .
    container_name: flower
    command: celery -A project --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    volumes:
      - ./project:/code/project
      - ./logs:/code/logs
    depends_on:
      - web
      - redis
