# Generated by Django 3.2.6 on 2021-12-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
            },
        ),
        migrations.CreateModel(
            name='TextScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Текстовый Экран',
                'verbose_name_plural': 'Текстовые экраны',
            },
        ),
        migrations.CreateModel(
            name='MultifieldScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('boolField', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Мульти Экран',
                'verbose_name_plural': 'Мульти экраны',
            },
        ),
    ]
