# Generated by Django 3.2.6 on 2021-12-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_auto_20211214_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TextScreen', 'Текст'), ('FileScreen', 'Файл'), ('ImageScreen', 'Изображение'), ('ComplexScreen', 'Мульти')], max_length=140, verbose_name='Тип')),
                ('title', models.CharField(max_length=140, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('key', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Экран',
                'verbose_name_plural': 'Экраны',
            },
        ),
        migrations.RemoveField(
            model_name='textscreen',
            name='parent',
        ),
        migrations.AddField(
            model_name='protocol',
            name='type',
            field=models.CharField(choices=[('TypeOne', 'Тип 1'), ('TypeOne', 'Тип 2'), ('TypeOne', 'Тип 3')], default=0, max_length=140, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MultifieldScreen',
        ),
        migrations.DeleteModel(
            name='TextScreen',
        ),
        migrations.AddField(
            model_name='screen',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='Протокол'),
        ),
    ]
