# Generated by Django 3.2.6 on 2021-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_auto_20211215_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='key',
            field=models.FloatField(),
        ),
    ]
