# Generated by Django 3.2.6 on 2021-12-30 05:46

from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_auto_20211227_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=protocol.models.directory_images, verbose_name='Изображение'),
        ),
    ]
