# Generated by Django 3.2.6 on 2021-12-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0007_screen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение')], max_length=140, verbose_name='Тип'),
        ),
    ]
